[package]
name = "big-brain"
version = "0.15.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2021"
description = "Rusty Utility AI library"
license = "Apache-2.0"
readme = "README.md"
keywords = ["utility-ai", "bevy", "ai", "ecs"]
categories = ["game-development"]
repository = "https://github.com/zkat/big-brain"
homepage = "https://github.com/zkat/big-brain"

[dependencies]
bevy = { version = "0.9.0", default-features = false }

[dev-dependencies]
bevy = { version = "0.9.0", default-features = true }
rand = { version = "0.8.5", default-features = false, features = ["small_rng", "std"] }

[features]
trace = []

[[example]]
name = "custom_measure"

[[example]]
name = "one_off"

[[example]]
name = "sequence"

[[example]]
name = "thirst"

[[example]]
name = "concurrent"