[package]
name = "big-brain"
version = "0.5.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"
description = "Rusty Utility AI library"
license-file = "LICENSE.md"
readme = "README.md"
keywords = ["utility-ai", "bevy", "ai", "ecs"]
categories = ["game-development"]
repository = "https://github.com/zkat/big-brain"
homepage = "https://github.com/zkat/big-brain"

[dependencies]
bevy = "0.5.0"
